---
# Set base path for Frigate
tmsetup_base_path_frigate: /frigate

# Proxy base paths
tmsetup_proxies:
  - name: dashboard
    base_path: /dashboard
    label: Dashboard
    pass: http://127.0.0.1:1880/dashboard/
    http_version: 1.1
    cache_bypass: $http_upgrade
    set_headers:
      - Host $host
      - X-Real-IP $remote_addr
      - X-Forwarded-For $proxy_add_x_forwarded_for
      - X-Forwarded-Proto $scheme
      - Upgrade $http_upgrade
      - Connection "upgrade"
      - Referer ""
  - name: frigate
    base_path: "{{ tmsetup_base_path_frigate }}"
    label: Frigate
    pass: http://127.0.0.1:5000/
    http_version: 1.1
    set_headers:
      - Host $host
      - X-Forwarded-For $proxy_add_x_forwarded_for
      - X-Forwarded-Proto $scheme
      - X-Forwarded-Scheme $scheme
      - Upgrade $http_upgrade
      - Connection "upgrade"
      - X-Ingress-Path "{{ tmsetup_base_path_frigate }}"
  - name: legacy_dashboard
    base_path: /ui
    label: Legacy Dashboard
    pass: http://127.0.0.1:1880/ui/
    http_version: 1.1
    cache_bypass: $http_upgrade
    set_headers:
      - Host $host
      - X-Real-IP $remote_addr
  - name: nodered
    base_path: /nr
    label: Node-RED admin console
    pass: http://127.0.0.1:1880/
    http_version: 1.1
    cache_bypass: $http_upgrade
    set_headers:
      - Host $host
      - X-Real-IP $remote_addr
      - X-Forwarded-For $proxy_add_x_forwarded_for
      - X-Forwarded-Proto $scheme
      - Upgrade $http_upgrade
      - Connection "upgrade"
  - name: go2rtc
    base_path: /feeds
    label: Go2RTC Feeds
    pass: http://host.containers.internal:1984/
    set_headers:
      - Host $host
      - X-Real-IP $remote_addr
      - Upgrade $http_upgrade
      - Connection "upgrade"
...
