---
- name: TMSetup - NGinx-RProxy-TM Setup - Create NGinx directory
  become: true
  loop:
    - { path: '{{ tmsetup_codedir }}', mode: '0750' }
    - { path: '{{ tmsetup_codedir }}/nginx-rproxy-tm', mode: '0750' }
    - { path: '{{ tmsetup_codedir }}/nginx-rproxy-tm/html', mode: '0755' }
  ansible.builtin.file:
    mode: '{{ item["mode"] }}'
    owner: '{{ tmsetup_codeowner }}'
    path: '{{ item["path"] }}'
    state: directory
  notify: Restart nginx-rproxy-tm.service

- name: TMSetup - NGinx-RProxy-TM Setup - Create NGinx config file
  become: true
  loop:
    - { path: 'nginx-rproxy-tm/Containerfile', mode: '0640' }
    - { path: 'nginx-rproxy-tm/nginx.conf', mode: '0640' }
    - { path: 'nginx-rproxy-tm/html/index.html', mode: '0644' }
  ansible.builtin.template:
    backup: false
    dest: '{{ tmsetup_codedir }}/{{ item["path"] }}'
    force: true
    group: '{{ tmsetup_codegroup }}'
    mode: '{{ item["mode"] }}'
    owner: '{{ tmsetup_codeowner }}'
    src: 'container/{{ item["path"] }}.j2'
  notify: Restart nginx-rproxy-tm.service

- name: TMSetup - NGinx-RProxy-TM Setup - Create NGinx quadlets
  become: true
  loop:
    - nginx-rproxy-tm.build
    - nginx-rproxy-tm.container
  ansible.builtin.template:
    dest: '/etc/containers/systemd/{{ item }}'
    group: root
    mode: '0644'
    owner: root
    src: 'container/nginx-rproxy-tm/{{ item }}.j2'
  notify: Restart nginx-rproxy-tm.service

- name: TMSetup - NGinx-RProxy-TM Setup - Build container
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: nginx-rproxy-tm-build.service
    state: started
  notify: Restart nginx-rproxy-tm.service

...
