---
- name: Create directory and set ownership
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ tmsetup_codeowner }}'
    group: '{{ tmsetup_codegroup }}'
    mode: '0755'
  notify: Restart tm-docker service
- name: Set node-red owner and group
  ansible.builtin.command: chown -R 1000:1000 {{ item }}