---
# Pineboard PCIE TPU setup tasks
- name: Enable PCIe connector at bootup
  become: true
  ansible.builtin.blockinfile:
    path: /boot/firmware/config.txt
    block: |
      # Enable the PCIe External connector.
      dtparam=pciex1
      kernel=kernel8.img
      # Enable Pineboards Hat Ai
      dtoverlay=pineboards-hat-ai
    append_newline: true
    prepend_newline: true
    create: true
    owner: root
    group: root
    mode: '0644'
    state: present

- name: Import tasks to create coral-edgetpu repo
  ansible.builtin.import_tasks:
    file: coraltpu_repo_setup.yml

- name: Install required packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - gasket-dkms=1.0-18
      - cmake
      - libedgetpu1-std
      - devscripts
      - debhelper
      - dkms

- name: Create apex udev rules to manage device permissions
  become: true
  ansible.builtin.copy:
    src: 65-apex.rules
    dest: /etc/udev/rules.d/65-apex.rules
    owner: root
    group: root
    mode: '0644'

- name: Create apex group
  become: true
  ansible.builtin.group:
    name: apex
    state: present

- name: Add codeowner to apex group
  become: true
  ansible.builtin.user:
    name: '{{ tmsetup_codeowner }}'
    groups: apex
    append: true
...
