---
# task file to start all services
- name: TMSetup - Start Services - Start and enable NetworkManager.service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: NetworkManager.service
    state: started

- name: TMSetup - Start Services - Start and enable traffic-monitor services
  become: true
  loop:
    - go2rtc_server.service
    - traffic-monitor.service
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
    state: "{{ 'stopped' if tmsetup_restart_required else 'started' }}"

...
