---
- name: Traffic Monitor Setup
  connection: local
  hosts: localhost
## User configurable variables. Defaults are defined here.
#  vars:
#    tmsetup_codeowner: 'tmadmin'
#    tmsetup_codedir: '/opt/traffic-monitor'
#    tmsetup_force_configs: false
  tasks:
    - name: Run tmsetup role
      ansible.builtin.import_role:
        name: tmsetup
...
