#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

sudo systemctl start go2rtc_server
sudo systemctl enable go2rtc_server
##-- /go2rtc


##-- docker compose build and start containers
docker compose \
   -f ~/code/frigate/docker-compose-frigate.yml \
   -f ~/code/nodered/docker-compose-node-red.yml \
    -f ~/code/influxdb/docker-compose-influxdb.yml \
  up --detach

# access frigate via http://[IP]:5000
# access node-red via http://[IP]:1880
