#!/bin/bash

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

#uncomment for re-downloading any dependencies that may need to be updated
#script/bootstrap

echo "==> Restarting go2rtc_server scripts..."
sudo systemctl stop go2rtc_server
sudo systemctl start go2rtc_server
sudo systemctl enable go2rtc_server

echo "==> Restarting node-red scripts..."
sudo systemctl stop nodered.service
sudo systemctl start nodered.service
sudo systemctl enable nodered.service

# node-red nodes install/reinstall
npm install --unsafe-perm --no-update-notifier --no-fund --only=production --prefix ~/.node-red/

echo "==> Removing existing docker containers..."
docker compose -f ~/code/compose.yaml down --remove-orphans

echo "==> Updating docker containers…"
# rebuild docker containers
docker compose -f ~/code/compose.yaml up --detach --force-recreate --build --remove-orphans

