#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

#uncomment for re-downloading any dependencies that may need to be updated
#script/bootstrap

echo "==> Updating docker containers…"

# rebuild docker containers
docker compose -f ~/code/compose.yaml up --detach --force-recreate --build --remove-orphans

