#!/bin/sh

# script/backup: Backup databases and/or media. 
#               Optionally specify which backup.
#               Optionally specify local, remote, or node-red locations.
#               Meant to be executed on host system.

cd "$(dirname "$0")/.."

#-- Database backup

#influx creates a directory of zipped files
docker exec influxdb influx backup /home/influxdb/backup/influxdb_bak
sudo tar -cvzf ~/code/backup/influxdb_$(date '+%Y-%m-%d_%H-%M').tar.gz ~/code/backup/influxdb_bak
sudo rm -rf ~/code/backup/influxdb_bak

#mongodb creates a single, bson archive file from mongodump
docker exec mongo sh -c 'exec mongodump --uri="mongodb://mongoadmin:mongodbpass@mongo:27017/tm-db?directConnection=true&authSource=admin&appName=mongosh+2.2.0" --archive' > ~/code/backup/mongodb.archive
sudo tar -cvzf ~/code/backup/mongodb_$(date '+%Y-%m-%d_%H-%M').tar.gz ~/code/backup/mongodb.archive
sudo rm -rf ~/code/backup/mongodb.archive
#to restore: docker exec tm-mongodb sh -c 'exec mongorestore -v --archive=/data/db/backup/mongodb_2024-04-24_17-32.archive'

#mongodb json export
# docker exec mongo sh -c 'exec mongoexport --uri="mongodb://mongoadmin:mongodbpass@mongo:27017/tm-db?directConnection=true&authSource=admin&appName=mongosh+2.2.0" --collection=events --db=tm-db --type=json' > ~/code/backup/events.json
# sudo tar -cvzf ~/code/backup/events_$(date '+%Y-%m-%d_%H-%M').tar.gz ~/code/backup/events.json
# sudo rm -rf ~/code/backup/events.json
# sudo rsync -azvv --progress -e ssh ~/code/backup/events_2024-06-12_11-03.tar.gz root@10.10.10.10:/mnt/user/data/traffic-monitor-dumps/databases/

#frigate creates a single archive with good compression
tar -cvpzf ~/code/backup/frigate_$(date '+%Y-%m-%d_%H-%M').tar.gz ~/code/frigate/config


# transfer databases to server
# sudo rsync -azvv --progress -e ssh ~/code/backup/frigate_2024-05-02_20-37.tar.gz root@10.10.10.10:/mnt/user/data/traffic-monitor-dumps/databases/
# sudo rsync -azvv --progress -e ssh ~/code/backup/influxdb_2024-06-03_08-40.tar.gz root@10.10.10.10:/mnt/user/data/traffic-monitor-dumps/databases/
# sudo rsync -azvv --progress -e ssh ~/code/backup/mongodb_2024-06-03_08-53.tar.gz root@10.10.10.10:/mnt/user/data/traffic-monitor-dumps/databases/


#-- Images backup -- only do this attached locally (maximize data transfer)
#clips remote backup
#sudo rsync -azvv --progress -e ssh frigate/storage root@10.10.10.10:/mnt/user/data/traffic-monitor-dumps/media/bak-$(date '+%Y-%m-%d')/frigate/

