---
# tmsetup handlers
- name: Restart go2rtc_server service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: go2rtc_server.service
    state: restarted

- name: Reload udev rules and trigger
  become: true
  ansible.builtin.shell: udevadm control --reload && udevadm trigger

- name: Restart journald service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: systemd-journald.service
    state: restarted

- name: Restart NetworkManager service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: NetworkManager.service
    state: restarted
  notify: Pause for 10 seconds

- name: Pause for 10 seconds
  ansible.builtin.pause:
    seconds: 10

- name: Restart frigate.service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: frigate.service
    state: "{{ 'stopped' if tmsetup_restart_required else 'restarted' }}"
  async: 600
  poll: 0

- name: Restart node-red-tm.service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: node-red-tm.service
    state: "{{ 'stopped' if tmsetup_restart_required else 'restarted' }}"
  async: 600
  poll: 0

- name: Restart plate-recognizer.service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: plate-recognizer.service
    state: "{{ 'stopped' if tmsetup_restart_required else 'restarted' }}"
  async: 600
  poll: 0

- name: TMSetup - Flag for reboot
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/handlers/reboot_handler.yml"

...
